// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class making_Pin_Code_table_Pin_attribute_null_allowed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(making_Pin_Code_table_Pin_attribute_null_allowed));
        
        string IMigrationMetadata.Id
        {
            get { return "202308192032189_making_Pin_Code_table_Pin_attribute_null_allowed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
