// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class First_Update_of_19_Aug_23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(First_Update_of_19_Aug_23));
        
        string IMigrationMetadata.Id
        {
            get { return "202308190647393_First_Update_of_19_Aug_23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
