// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class First_update_of_20_AUG_23_with_pin_code_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(First_update_of_20_AUG_23_with_pin_code_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202308200842197_First_update_of_20_AUG_23_with_pin_code_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
