// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Create_1_to_1_Relation_between_User_to_Tourist_Profile_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_1_to_1_Relation_between_User_to_Tourist_Profile_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "202308031559234_Create_1_to_1_Relation_between_User_to_Tourist_Profile_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
