// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Tourist_DAL_Complete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tourist_DAL_Complete));
        
        string IMigrationMetadata.Id
        {
            get { return "202308171818460_Tourist_DAL_Complete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
